[log]
mode = "on"
timing = false

[log.stdout]
level = "warn"

[log.file]
level = "info"
# path = "~/.cache/taro/taro.log"

[persistence]
enabled = true
type = "sqlite"
max_records = -1
# max_age = "#ISO 8601 duration format"
# database = "~/.local/share/taro/jobs.db"

[plugins]
enabled = false
# load = ["taro_sns"]
